### Zod Parser Test
GET http://[::1]:3000/api/zod-parser-test?name=john&age=5 HTTP/1.1

### Base API Error Test
GET http://[::1]:3000/api/api-error-test HTTP/1.1

### Products
GET http://[::1]:3000/api/products?skip=50&limit=20 HTTP/1.1