### Zod Parser Test
GET http://[::1]:3000/api/zod-parser-test?name=john&age=5 HTTP/1.1

### Base API Error Test
GET http://[::1]:3000/api/api-error-test HTTP/1.1

### Products
GET http://[::1]:3000/api/products?page=1&brand=Samsung,Apple&price=gt.299.99&q=apple&sortBy=price HTTP/1.1