// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/zod-parser-test': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/zod-parser-test.get').default>>>>
    }
  }
}
export {}